=== worldsbestcode/2S0t2a4r0g3a1z5r/fxweb/python/fx/documentation/raml/application/guardian/json_schema/ObjectPostSchema.json
{ "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Object POST Request Body",
  "description": "JSON format for Object POST Request Body",
  "type": "object",
  "properties": {
    "method": { "type": "string" },
    "objectType": { "type": "string" },
    "quantity": { "type": "integer" },
    "request": { "$ref": "Filter.json" }
  }
}

=== worldsbestcode/2S0t2a4r0g3a1z5r/fxweb/python/fx/documentation/raml/application/guardian/json_example/ObjectPostExample2.json
{
  "method": "retrieve",
  "objectType": "Filter",
  "quantity": 10,
  "request": {
    "manager": "KEY",
    "chunk": 0,
    "chunkSize": 10,
    "chunkCount": 1,
    "matchCount": 1,
    "flags": [
    ],
    "filterType": "RESULTS",
    "sortAscending": false,
    "distinctOn": "",
    "objectIDs": {}
  }
}

=== worldsbestcode/2S0t2a4r0g3a1z5r/fxweb/python/fx/documentation/raml/application/guardian/json_example/ObjectPostExample.json
{
  "method": "retrieve",
  "objectType": "Filter",
  "quantity": 10,
  "request": {
    "manager": "KEYS",
    "chunk": 0,
    "chunkSize": 100,
    "chunkCount": 1,
    "matchCount": 1,
    "flags": [
      "INACTIVE_INCLUDE",
      "GUI_QUERY",
      "DESCENDANTS",
      "NO_COUNT"
    ],
    "filterType": "IDENTIFIERS",
    "sortAscending": false,
    "distinctOn": "name",
    "objectIDs": {}
  }
}
